import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import AppProvidersWrapper from "../providers/AppProvidersWrapper";
import QuickViewModal from "./components/shop/QuickViewModal";


export const metadata: Metadata = {
  title: "FindKarko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``} id='modal-ts'>

      <AppProvidersWrapper>
        {children}
      </AppProvidersWrapper>
      <QuickViewModal />

      </body>

    </html>
  );
}
