import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import AppProvidersWrapper from "../providers/AppProvidersWrapper";
import QuickViewModal from "./components/shop/QuickViewModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FindKarko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} id='modal-ts'>
      <AppProvidersWrapper>
        {children}
      </AppProvidersWrapper>
      <QuickViewModal />

      </body>

    </html>
  );
}
